name: terraform-plan

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: terraform/

    env:
      ENVIRONMENT: prod
      TF_CLOUD_PROJECT: ByItsCover_PROD
      TF_WORKSPACE: bic-suggest-prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Hashicorp - Terraform setup
        uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: |
          terraform fmt -recursive
          terraform validate
        continue-on-error: false

      - name: Render Terraform Docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./terraform
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Terraform Plan
        run: terraform plan -var-file=variables/${{ env.ENVIRONMENT }}.tfvars
